Gson interface
Polyfrost/OneConfig pull request #109
Opened 2022-08-23 16:52 UTC by DeDiamondPro

## Description

Add gson-interface, this allows you to register serializers and deserializers with ease
see: [https://github.com/mintern/gson-interface/blob/master/InterfaceExample.java](https://github.com/mintern/gson-interface/blob/master/InterfaceExample.java)

## Related Issue(s)

## Checklist
- [X] I made a clear description of what was changed
- [X] I stated why these changes were necessary
- [X] I updated documentation or said what needs to be updated
- [X] I made sure these changes are backwards compatible
- [X] This pull request is for one feature/bug fix

2022-08-23 16:53 UTC, Wyvest approved these changes

2022-08-23 17:28 UTC, nxtdaydelivery submitted a review, later dismissed
lgtm yesyes

2022-08-23 17:29 UTC, nxtdaydelivery commented
I won't merge because I assume you wanted moon to check licensing

2022-08-23 17:41 UTC, MoonTidez requested changes
see the comments
U put copyright stuff in the wrong place

2022-08-23 17:41 UTC, MoonTidez commented on src/main/java/cc/polyfrost/oneconfig/config/gson/gsoninterface/GsonContext.java
> + * Copyright (c) 2012, Brandon Mintern, EasyESI, Berkeley, CA
nice small (c)

2022-08-23 17:41 UTC, MoonTidez commented on src/main/java/cc/polyfrost/oneconfig/config/gson/gsoninterface/GsonContext.java
> + * Copyright (c) 2012, Brandon Mintern, EasyESI, Berkeley, CA
also add the copyright for outside stuff (Brandon etc) to the `LICENSE NOTICE FOR ADAPTED CODE`

2022-08-23 17:41 UTC, MoonTidez commented on src/main/java/cc/polyfrost/oneconfig/config/gson/gsoninterface/JsonDeserialization.java
> + * Copyright (c) 2012, Brandon Mintern, EasyESI, Berkeley, CA
see other comments

2022-08-23 17:41 UTC, MoonTidez commented on src/main/java/cc/polyfrost/oneconfig/config/gson/gsoninterface/InterfaceAdapterFactory.java
> + * Copyright (c) 2012, Brandon Mintern, EasyESI, Berkeley, CA
see other comments

2022-08-23 19:50 UTC, Wyvest approved these changes

2022-08-24 18:00 UTC, nxtdaydelivery approved these changes
lgtm

2022-08-24 18:19 UTC, merged