msc: cleanup mixins
Polyfrost/OneConfig pull request #178
Opened 2022-11-27 17:29 UTC by Wyvest

## Description

## Related Issue(s)

## Checklist
- [ ] I made a clear description of what was changed
- [ ] I stated why these changes were necessary
- [ ] I updated documentation or said what needs to be updated
- [ ] I made sure these changes are backwards compatible
- [ ] This pull request is for one feature/bug fix

2022-11-27 17:30 UTC, xtrm-en requested changes

2022-11-27 17:30 UTC, xtrm-en commented on versions/1.16.5-forge/src/main/java/cc/polyfrost/oneconfig/internal/mixin/KeyboardMixin.java
> +        System.out.println("gdgjasdkogdsagikoDSJMGdskogjmds");
damn

2022-11-27 18:08 UTC, pauliesnug commented on versions/1.16.5-forge/src/main/java/cc/polyfrost/oneconfig/internal/mixin/KeyboardMixin.java
> +        System.out.println("gdgjasdkogdsagikoDSJMGdskogjmds");
samesies

2022-11-27 18:29 UTC, Rattlyy commented on versions/1.16.5-forge/src/main/java/cc/polyfrost/oneconfig/internal/mixin/KeyboardMixin.java
> +        System.out.println("gdgjasdkogdsagikoDSJMGdskogjmds");
real

2022-11-27 22:39 UTC, xtrm-en submitted a review, later dismissed
yea

2022-12-04 14:18 UTC, xtrm-en approved these changes
lgtm

2022-12-04 14:19 UTC, pauliesnug approved these changes
llll (looks looks looks looks)

2022-12-04 14:20 UTC, merged