Icon Tweaks
Polyfrost/OneConfig pull request #229
Opened 2023-02-05 04:13 UTC by xtrm-en

## Description
This PR brings the following features:
- Removes the Mod Card for the `Forge Mod Loader` (modid: `FML`) mod, as it's not useful to display
- Adds a Mod Icon for the `MinecraftForge` (modid: `Forge`) mod
- ModCard icons now render up to a `64x64` resolution, instead of the previous `48x48`.
  - Subsequently, the rendering code for ModCard icons has been moved

## Checklist
- [x] I made a clear description of what was changed
- [x] I stated why these changes were necessary
- [x] I updated documentation or said what needs to be updated
- [x] I made sure these changes are backwards compatible
- [x] This pull request is for one feature/bug fix

2023-02-05 15:12 UTC, Wyvest requested changes
fine overall but can you implement rectangle icons and where's the forge icon

2023-02-05 16:28 UTC, xtrm-en commented
rectangle icons would be possible but kinda bad design-wise imo

> and where's the forge icon

[wdym](https://github.com/Polyfrost/OneConfig/pull/229/commits/23e46da213997f077c2703419fb393d3ea7a1f67)

2023-02-05 16:30 UTC, Wyvest commented
> rectangle icons would be possible but kinda bad design-wise imo
> 

mmm but like our fallback is literally text (which acts like a rectangle)

> 
> > and where's the forge icon
> 
> 
> 
> [wdym](https://github.com/Polyfrost/OneConfig/pull/229/commits/23e46da213997f077c2703419fb393d3ea7a1f67)

i love github mobile

2023-02-05 16:32 UTC, xtrm-en commented
then ways of implementing it would be to either:
- look at the aspect ratio of the provided icon and use that to determine the width from the fixed height
  - idk if that would work for svgs
- let the user provide the icon dimentions  
  - they're gonna fuck it up (probably)

2023-02-05 16:34 UTC, Wyvest commented
> then ways of implementing it would be to either:
> 
> - look at the aspect ratio of the provided icon and use that to determine the width from the fixed height
> 
>   - idk if that would work for svgs
> 
> - let the user provide the icon dimentions  
> 
>   - they're gonna fuck it up

let the users provide it, it's not our fault if it's stretched as hell

2023-02-05 16:35 UTC, xtrm-en commented
should we postpone rectangle icons to config rewrite?

2023-02-05 16:35 UTC, Wyvest commented
why though

2023-02-05 16:38 UTC, xtrm-en commented
because the `Mod` constructor is already cluttered enough as-is, it's not an urgent feature, and I'd like to add a bit more than just dimensions

2023-02-05 16:39 UTC, Wyvest commented
i mean slightly urgent we have devs waiting for this

2023-02-05 16:39 UTC, xtrm-en commented
oh? well alright then

2023-02-05 23:58 UTC, Wyvest requested changes

2023-02-05 23:58 UTC, Wyvest commented on versions/src/main/java/cc/polyfrost/oneconfig/internal/OneConfig.java
> +import net.minecraftforge.fml.common.ModMetadata;
put this in the forge comment block

2023-02-06 18:51 UTC, Wyvest approved these changes
yes

2023-02-06 18:56 UTC, merged