draw centered text
Polyfrost/OneConfig pull request #276
Opened 2023-07-23 23:44 UTC by badjavadev

## Description

i need this i need this i need this i need this i need this i need this

## Related Issue(s)

## Checklist
- [ ] I made a clear description of what was changed
- [ ] I stated why these changes were necessary
- [ ] I updated documentation or said what needs to be updated
- [ ] I made sure these changes are backwards compatible
- [ ] This pull request is for one feature/bug fix

2023-07-23 23:57 UTC, badjavadev commented
yes this is useless

2023-07-24 08:34 UTC, Wyvest requested changes
apart from that one thing it looks good

2023-07-24 08:34 UTC, Wyvest commented on src/main/java/cc/polyfrost/oneconfig/gui/elements/config/ConfigKeyBind.java
> -        } else if (text.equals("")) text = "None";
what

2023-07-24 13:37 UTC, badjavadev commented on src/main/java/cc/polyfrost/oneconfig/gui/elements/config/ConfigKeyBind.java
> -        } else if (text.equals("")) text = "None";
idk what is this

2023-07-24 15:07 UTC, TheKodeToad commented on src/main/java/cc/polyfrost/oneconfig/renderer/NanoVGHelper.java
> +     * Draws a Centered String with the given parameters.
```suggestion
     * Draws a centered String with the given parameters.
```

2023-07-28 01:07 UTC, closed without merging