Config Checker
Polyfrost/OneConfig pull request #67
Opened 2022-07-24 14:32 UTC by nxtdaydelivery

## Description
it checks the configs for invalid field types before the game launches and gives much more helpful error messages
it also fixes the bug where it try to serialise Runnables, creating the error message 'Unable to deserialize Runnable in config'

## Related Issue(s)

## Checklist
- [ ] I made a clear description of what was changed
- [ ] I stated why these changes were necessary
- [ ] I updated documentation or said what needs to be updated
- [ ] I made sure these changes are backwards compatible
- [ ] This pull request is for one feature/bug fix

2022-07-24 14:36 UTC, DeDiamondPro submitted a review, later dismissed

2022-07-25 01:04 UTC, Wyvest requested changes

2022-07-25 01:04 UTC, Wyvest commented on src/main/java/cc/polyfrost/oneconfig/config/core/InvalidTypeException.java
> +public class InvalidTypeException extends RuntimeException {
can you remove the javadocs in this class?

2022-07-25 08:46 UTC, Wyvest approved these changes

2022-07-25 10:39 UTC, DeDiamondPro approved these changes

2022-07-25 10:39 UTC, merged